development:
  adapter: postgresql
  encoding: unicode
  database: hillbomber_development
  username: hillbomber
  password: ""

test:
  adapter: postgresql
  encoding: unicode
  database: hillbomber_test
  username: hillbomber
  password: ""

production:
  adapter: postgresql
  encoding: unicode
  database: hillbomber_production
  username: hillbomber
  password: ""
